### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by yiyungent** [yiyungent/PluginCore#31]
```
Unhandled exception. System.TypeLoadException: Method 'ConfigureServices' in type 'UHubPlugin.UHubPlugin' from assembly 'UHubPlugin, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at PluginCore.lmplements.PluginFinder.EnablePluginsFull[TPlugin]()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PluginCore.AspNetCore.Extensions.PluginCoreStartupExtensions.AddPluginCore(IServiceCollection services)
   at KnifeHub.Web.Program.Main(String[] args) in F:\Repos\KnifeHubPro\src\KnifeHub\src\KnifeHub.Web\Program.cs:line 29
```

**Comment by yiyungent** [comment]
```csharp
public void ConfigureServices(IServiceCollection services)
```

实现

```csharp
PluginCore.IPlugins.IStartupPlugin.ConfigureServices(IServiceCollection services);
```

怀疑与 `IServiceCollection` 有关, 位于 `Microsoft.Extensions.DependencyInjection.Abstractions.dll`
